Jenkinsfile_CNP, Jenkinsfile_nightly, catalog-info.yaml, charts/fis-ds-web/Chart.yaml, charts/fis-ds-web/values.yaml, config/default.yaml, config/development.yaml, docker-compose.yml, infrastructure/main.tf, infrastructure/variables.tf, sonar-project.properties, src/main/app/case/CaseApi.ts, src/main/app/controller/GetController.ts, src/main/assets/js/cookie.ts, src/main/modules/properties-volume/index.ts, src/main/steps/common/constants/apiConstants.ts, src/test/e2e/config.js, yarn-error.log
=> fis to sptribs substitutions

charts/sptribs-frontend/Chart.yaml, charts/sptribs-frontend/values.yaml, config/default.yaml, config/development.yaml, infrastructure/main.tf, src/main/modules/properties-volume/index.ts
=> creating new PR

src/main/resources/representation-qualified/translation.json
https://tools.hmcts.net/jira/browse/ST-556
Fix bug with field validation
```
[ ] Yes
[x] No
```
=> ST-556 Fix wrong field name for error text

src/main/public/main-dev.js, src/main/resources/representative-details/translation.json
=> implemented review comments

src/main/resources/application-submitted/translation.json, src/main/steps/edge-case/application-submitted/content.test.ts, src/main/steps/edge-case/application-submitted/content.ts, src/main/steps/edge-case/application-submitted/template.njk
=> Confirmation screen

src/main/resources/upload-other-information/translation.json, src/main/steps/edge-case/check-your-answers/utils.ts, src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts, src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts
https://tools.hmcts.net/jira/browse/ST-298
Allows user to continue past other information screen without uploading any documents.
```
[ ] Yes
[x] No
```
=> ST-298 Do not error if no docs uploaded

src/main/steps/edge-case/application-submitted/template.njk
=> Removed back link from confirmation page

src/main/resources/application-submitted/translation.json, src/main/resources/check-your-answers/translation.json, src/main/resources/representation-qualified/translation.json, src/main/resources/representation/translation.json, src/main/resources/representative-details/translation.json, src/main/resources/subject-contact-details/translation.json, src/main/resources/subject-details/translation.json, src/main/resources/upload-appeal-form/translation.json, src/main/resources/upload-other-information/translation.json, src/main/resources/upload-supporting-documents/translation.json
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x ] No
```
=> Changed service name to Appeal to the First-tier Tribunal

src/main/resources/upload-other-information/translation.json
Fix error message
```
[ ] Yes
[x] No
```
=> ST-298 Fix file count error message

src/main/resources/landing/translation.json
=> changed service name to Appeal to the First-tier Tribunal on landing page

config/default.yaml, src/main/app/controller/PostController.test.ts, src/main/app/controller/PostController.ts
=> ST-926 Create case after second screen

src/main/steps/error/content.ts
=> ST-930 , improve Internal error page

src/main/steps/error/content.ts
=> ST-930 , update error message 

src/main/steps/edge-case/equality/get.test.ts, src/main/steps/edge-case/equality/get.ts
https://tools.hmcts.net/jira/browse/ST-931
Do not invoke PCQ if under 16
```
[ ] Yes
[x] No
```
=> ST-931 Do not invoke PCQ if under 16

src/main/steps/edge-case/equality/get.test.ts, src/main/steps/edge-case/equality/get.ts
https://tools.hmcts.net/jira/browse/ST-931
Fix bug where age check was a month out
```
[ ] Yes
[x] No
```
=> ST-931 Fix bug where age check was a month out

.gitignore, config/development.yaml, src/main/app/case/CaseApi.ts, src/main/modules/properties-volume/index.ts
https://tools.hmcts.net/jira/browse/ST-1125
Changes needed to integrate with case api
```
[ ] Yes
[x] No
```
=> ST-1125 Changes for integration with case api

charts/sptribs-frontend/values.yaml
=> s2s-secret has been deleted

charts/sptribs-frontend/Chart.yaml, charts/sptribs-frontend/values.yaml
=> s2s-secret-sptribs-frontend has been added

src/main/routes/authless/path.ts, src/main/routes/authless/routes.ts
=> ST-1384 landing page, routing and redirect

src/main/app/auth/service/get-service-auth-token.ts
N/A
Remove debugging Service Auth Token log output used during lower environment setup.
```
[ ] Yes
[x] No
```
=> Removing debugging Service Auth Token log output

charts/sptribs-frontend/values.preview.template.yaml
=> Preview env - DO NOT MERGE

src/main/app/case/CaseApi.ts, src/main/app/case/formatter/address.ts, src/main/app/controller/GetController.ts, src/main/app/controller/PostController.ts, src/main/modules/session/index.ts, src/main/steps/edge-case/subject-details/content.ts, src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts, src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts, src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.ts
https://tools.hmcts.net/jira/browse/ST-1459
```
[ ] Yes
[ x] No
```
=> ST-1459-console.log clear

infrastructure/main.tf
https://github.com/hmcts/cnp-module-redis/pull/33 is now merged
=> Back to master branch of the redis module

charts/sptribs-frontend/Chart.yaml, src/main/app/rpe/RpeApi.ts, src/main/modules/fileupload/index.test.ts, src/main/modules/helmet/index.test.ts, src/main/steps/common/functions/mapSummaryListContent.test.ts
https://tools.hmcts.net/jira/browse/ST-1403
```
[ ] Yes
[x ] No
```
=> ST-1403-unit tests-added

src/main/app/case/answers/formatDate.test.ts, src/main/app/case/case.test.ts, src/main/app/case/formatter/address.test.ts, src/main/modules/appinsights/index.test.ts
https://tools.hmcts.net/jira/browse/ST-1403
```
[ ] Yes
[x ] No
```
=> ST-1403-unit tests

Jenkinsfile_nightly, src/main/app/controller/GetController.ts, src/main/modules/session/index.test.ts, src/main/modules/session/index.ts
https://tools.hmcts.net/jira/browse/ST-1475
https://tools.hmcts.net/jira/browse/ST-1447
```
[ ] Yes
[x ] No
```
=> ST-1475-cookie security/ST-1447-nightly-pipeline

src/main/app/controller/GetController.ts, src/main/modules/session/index.test.ts, src/main/modules/session/index.ts
https://tools.hmcts.net/jira/browse/ST-1475
```
[ ] Yes
[ x] No
```
=> ST-1475-cookie security

package.json
https://tools.hmcts.net/jira/browse/ST-1442
```
[ ] Yes
[x ] No
```
=> ST-1442-node upgrade

src/main/resources/check-your-answers/translation.json
https://tools.hmcts.net/jira/browse/ST-1367
fixed label
```
[ ] Yes
[ x] No
```
=> ST-1367 : fixed label

charts/sptribs-frontend/values.preview.template.yaml, config/default.yaml
ST-1454
Pointing config to R3 PR.
```
=> Master point to r3

config/default.yaml, src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.ts, src/main/steps/edge-case/upload-other-information/uploadDocPostController.ts, src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.ts
https://tools.hmcts.net/jira/browse/ST-1504
```
[ ] Yes
[ ] No
```
=> ST-1504 Document size changed

src/test/e2e/tests/ErrorTriggers_test.js, src/test/e2e/tests/SubmitApplication_test.js
Temporary disable of E2E
```
[ ] Yes
[X] No
```
=> Temporary disable due to AAT error

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/ST-1179
St-117 smoke test report added for aat
```
[ ] Yes
[ ] No
```
=> St-1179 smoke test report added for aat

.github/renovate.json, renovate.json
https://tools.hmcts.net/jira/browse/ST-1609
done
```
[ ] Yes
[x] No
```
=> Fixed renovate configuration

src/test/e2e/tests/1_SubmitApplication_test.js, src/test/e2e/tests/BackButton_test.js, src/test/e2e/tests/ErrorTriggers_test.js
Reactivating and updating frontend tests
- [NO] Does this PR introduce a breaking change
=> 1189 reactivate tests

charts/sptribs-frontend/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSSTCI-12
Update nodejs chart version
=> DTSSTCI-12

src/test/e2e/tests/1_SubmitApplication_test.js, src/test/e2e/tests/BackButton_test.js, src/test/e2e/tests/ErrorTriggers_test.js
Disabling E2E's as AAT is broken
=> Disabling E2E

.eslintrc.js, src/main/app/address/SelectAddressPostControllerBase.test.ts, src/main/steps/common/components/address-international.test.ts
https://tools.hmcts.net/jira/browse/DTSSTCI-13
Fixed no-console, no-non-null-assertion and commented tests warnings
=> Fixed few warnings reported in yarn lint

src/test/e2e/config.js
Changing the default, locally ran URL to reflect current AAT address.
=> Changing default URL

src/test/e2e/tests/1_SubmitApplication_test.js, src/test/e2e/tests/BackButton_test.js, src/test/e2e/tests/ErrorTriggers_test.js
Disabling E2E's due to master pipeline failing
=> disabling E2E's for master pipeline failure

Jenkinsfile_CNP
Updating the Jenkins_CNP to match current AAT frontend links
=> Jenkins AAT links update

src/test/e2e/tests/1_SubmitApplication_test.js, src/test/e2e/tests/BackButton_test.js, src/test/e2e/tests/ErrorTriggers_test.js, src/test/e2e/tests/smoke_test.js
Reactivating tests now that Master E2E pipeline is working
=> Reactivating E2E's now master pipeline is working

src/main/routes/authless/views/landing.njk, src/main/steps/common/page.njk, src/main/views/template.njk
https://tools.hmcts.net/jira/browse/ST-1685
changes for hiding Welsh Language Toggle
=> changes for hiding Welsh Language Toggle

Jenkinsfile_nightly
changed the nightly pipeline configuration in jenkins_nightly file
=> ST-1184 changed the nightly pipeline configuration in jenkins_nightly file

Jenkinsfile_nightly, saucelabs.conf.js
Added config for nightly pipeline to saucelabs.conf.js file
=> ST-1184 Added config for nightly pipeline to saucelabs.conf.js file

Jenkinsfile_nightly
Added config for nightly pipeline to jenkins_nightly file
=> ST-1184 Added config for nightly pipeline to jenkins_nightly file

package.json
changes made in package.json file
=> ST-1184 changes made in package.json file

package.json, src/test/e2e/pages/login.page.js
=> ST-1184 Changed login page details

.gitignore, Jenkinsfile_CNP, codecept.conf.js, package.json, playwright.config.ts, src/test/e2e/helpers/browser_helper.js, src/test/e2e/helpers/dump_browser_logs_helper.js, src/test/e2e/helpers/event_listener.js, src/test/e2e/helpers/hooks_helper.js, src/test/e2e/pages/CheckYourAnswers.page.js, src/test/e2e/pages/Representation.page.js, src/test/e2e/pages/RepresentationQualified.page.js, src/test/e2e/pages/RepresentativeDetails.page.js, src/test/e2e/pages/SubjectContactDetails.page.js, src/test/e2e/pages/SubjectDetails.page.js, src/test/e2e/pages/UploadAppealForm.page.js, src/test/e2e/pages/UploadOtherInformation.page.js, src/test/e2e/pages/UploadSupportingDocuments.page.js, src/test/e2e/pages/applicationSubmitted.page.js, src/test/e2e/pages/login.page.js, src/test/e2e/tests/1_SubmitApplication_test.js, yarn.lock
Converting the E2E tests to use playwright as a test driver, instead of puppeteer.
=> E2E Playwright conversion

codecept.conf.js, package.json
Adding cross browser testing for a mobile device, and also using workers instead of multiple to make the tests less flaky
=> Adding mobile device testing

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/DTSSTCI-349
Bumped up follow-redirects package
=> DTSSTCI-349: Fixed dependency issue

package.json, yarn-audit-known-issues, yarn.lock
https://tools.hmcts.net/jira/browse/DTSSTCI-474
Bumped up NPM IP package
=> DTSSTCI-474: Fix CVE issue of NPM IP package

charts/sptribs-frontend/Chart.yaml, charts/sptribs-frontend/values.yaml, config/default.yaml, src/main/modules/helmet/index.ts, src/main/modules/nunjucks/index.ts, src/main/modules/properties-volume/index.ts, src/main/routes/authless/views/authless-templates.njk, src/main/steps/common/page.njk
https://tools.hmcts.net/jira/browse/DTSSTCI-557
Add dynatrace tags to sptribs dss submit
=> DTSSTCI-557

package.json, yarn-audit-known-issues, yarn.lock
https://tools.hmcts.net/jira/browse/DTSSTCI-668
bumped up follow-redirects
=> DTSSTCI-668: Fix for CVE-2024-28849

charts/sptribs-frontend/Chart.yaml, charts/sptribs-frontend/values.yaml
https://tools.hmcts.net/jira/browse/DTSSTCI-396
Configure autoscaling for sptribs frontend
=> DTSSTCI-396

src/main/app/controller/GetController.ts, src/main/modules/oidc/index.ts, src/main/steps/common/common.content.ts, src/main/steps/edge-case/check-your-answers/content.test.ts, src/main/steps/edge-case/cookies/template.njk, src/main/steps/timed-out/get.test.ts, src/main/steps/timed-out/get.ts, src/main/steps/url-utils.test.ts, src/main/steps/url-utils.ts
https://tools.hmcts.net/jira/browse/DTSSTCI-675
Implement time out page for DSS Submit Case
=> DTSSTCI-675

charts/sptribs-frontend/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSSTCI-711
Bump nodejs chart version to v3.1.0
=> DTSSTCI-711

src/main/app/auth/user/oidc.test.ts, src/main/app/auth/user/oidc.ts, src/main/app/case/CaseApi.test.ts, src/main/app/controller/AppRequest.ts, src/main/app/controller/GetController.ts, src/main/app/controller/PostController.ts, src/main/app/controller/UploadController.ts, src/main/modules/oidc/index.ts, src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.ts
Restrict access to DSS Submit citizen UI to only users with citizen user role
https://tools.hmcts.net/jira/browse/DTSSTCI-667
=> DTSSTCI-667

package.json, webpack.config.js, yarn.lock
Set devtools to false in webpack config
https://tools.hmcts.net/jira/browse/DTSSTCI-74
=> DTSSTCI-74

src/main/steps/privacy-policy/content.test.ts, src/main/steps/privacy-policy/content.ts, src/main/steps/privacy-policy/template.njk
Update privacy policy in DSS Submit Case
NOTE: Welsh content updates to be completed as part of https://tools.hmcts.net/jira/browse/DTSSTCI-745
https://tools.hmcts.net/jira/browse/DTSSTCI-744
=> DTSSTCI-744

config/default.yaml, config/development.yaml, src/main/app/controller/UploadController.test.ts, src/main/app/controller/UploadController.ts, src/main/modules/fileupload/index.test.ts, src/main/modules/fileupload/index.ts, src/main/resources/upload-appeal-form/translation.json, src/main/resources/upload-other-information/translation.json, src/main/resources/upload-supporting-documents/translation.json, src/main/steps/edge-case/upload-appeal-form/uploadDocPostController.test.ts, src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts, src/main/steps/edge-case/upload-supporting-documents/uploadDocPostController.test.ts
Update config to allow up to 100MB file uploads
https://tools.hmcts.net/jira/browse/DTSSTCI-754
=> DTSSTCI-754

charts/sptribs-frontend/values.preview.template.yaml, src/main/server.ts
Disable rate limiter in preview
https://tools.hmcts.net/jira/browse/DTSSTCI-758
=> DTSSTCI-758

src/main/resources/representation-qualified/translation.json, src/main/resources/representation/translation.json
Applied fix from DTSSTCI-274 in translation.json to change 'label' to 'title'.
https://tools.hmcts.net/jira/browse/DTSSTCI-817
=> DTSSTCI-817

src/main/steps/edge-case/upload-appeal-form/template.njk, src/main/steps/edge-case/upload-other-information/template.njk, src/main/steps/edge-case/upload-supporting-documents/template.njk
Added some indentation and enabled the display of inline error messages on file upload pages.
https://tools.hmcts.net/jira/browse/DTSSTCI-731
=> DTSSTCI-731

src/main/app/controller/UploadController.ts, src/main/app/form/validation.test.ts, src/main/app/form/validation.ts, src/main/resources/representative-details/translation.json, src/main/resources/upload-other-information/translation.json, src/main/steps/edge-case/representative-details/content.test.ts, src/main/steps/edge-case/representative-details/content.ts, src/main/steps/edge-case/upload-other-information/content.ts, src/main/steps/edge-case/upload-other-information/uploadDocPostController.test.ts
Add validation for markdown links
https://tools.hmcts.net/jira/browse/DTSSTCI-842
=> DTSSTCI-842

package.json, yarn.lock
Bump packages in resolutions to resolve dependency check failures
https://tools.hmcts.net/jira/browse/DTSSTCI-879
=> DTSSTCI-879

src/main/steps/accessibility-statement/content.ts
Add Welsh translations for Accessibility Statement
https://tools.hmcts.net/jira/browse/DTSSTCI-748
=> DTSSTCI-748

src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.test.ts, src/main/steps/edge-case/check-your-answers/checkYourAnswerPostController.ts, src/main/steps/edge-case/equality/get.test.ts
Add test cases for lang var in CYA tests
https://tools.hmcts.net/jira/browse/DTSSTCI-73
=> DTSSTCI-73

src/main/steps/edge-case/equality/get.ts
Fix pcq language parameter
https://tools.hmcts.net/jira/browse/DTSSTCI-938
=> DTSSTCI-938

package.json, yarn.lock
Add resolutions for send package to resolve dependency check error
https://tools.hmcts.net/jira/browse/DTSSTCI-1093
=> DTSSTCI-1093

package.json, yarn.lock
For audit purposes: This PR was raised off the back of a request from the sptribs team to do this on their behalf as they haven't got anyone to hand who can do this for them right now. I'm force-merging due to this.
=> Upgrade axios to save nightly builds

src/test/java/build.gradle
Remove jitpack dependency
https://tools.hmcts.net/jira/browse/DTSSTCI-
**Before merging a pull request make sure that:**
**If this ticket will have any visible impact on users and is not behind a feature toggle, make sure that:**
Note that bug fixes, dependency updates and technical tasks do not directly impact the user experience and can be merged without QA and PO review.
=> Remove jitpack dependency

src/test/java/build.gradle
Enter a description.
https://tools.hmcts.net/jira/browse/DTSSTCI-
**Before merging a pull request make sure that:**
**If this ticket will have any visible impact on users and is not behind a feature toggle, make sure that:**
Note that bug fixes, dependency updates and technical tasks do not directly impact the user experience and can be merged without QA and PO review.
=> Fix fortify

package.json, yarn.lock
Enter a description.
https://tools.hmcts.net/jira/browse/DTSSTCI-
**Before merging a pull request make sure that:**
**If this ticket will have any visible impact on users and is not behind a feature toggle, make sure that:**
Note that bug fixes, dependency updates and technical tasks do not directly impact the user experience and can be merged without QA and PO review.
=> Update superagent to 10.2.2+

package.json, yarn.lock
Enter a description.
https://tools.hmcts.net/jira/browse/DTSSTCI-
**Before merging a pull request make sure that:**
**If this ticket will have any visible impact on users and is not behind a feature toggle, make sure that:**
Note that bug fixes, dependency updates and technical tasks do not directly impact the user experience and can be merged without QA and PO review.
=> Upgrade express-session version
